version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: first_serverpod
      POSTGRES_PASSWORD: "58V7POXn8-jEtKX9yIDtaBIEu7sgihXJ"
    volumes:
      - first_serverpod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "vFm5ExIOHoAdKFdSi7b0KUrDget6GyRq"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  first_serverpod_data:
